[package]
name = "clip-sync"
authors = ["Chen Xu <windoze@0d0a.com>"]
version = "0.1.0"
edition = "2021"
description = "A clipboard sync tool"
rust-version = "1.75.0"

[dependencies]
anyhow = "1"
log = "0.4"
env_logger = "0.10"
clap = { version = "4", features = ["derive"] }
clap-verbosity-flag = "2"
futures = { version = "0.3" }
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
platform-dirs = "0.3"
futures-util = "0.3"
poem = { version = "1", features = ["websocket", "rustls", "static-files"] }
tantivy = { version = "0.21" }
tantivy-jieba = "0.10.0"
chrono = "0.4"

rumqttc = { version = "0.23", optional = true }
clipboard = { version = "0.5", optional = true }
clipboard-master = { version = "3", optional = true }
gethostname = { version = "0.4", optional = true }
random-string = { version = "1", optional = true }
tokio-tungstenite = { version = "0.21.0", features = ["rustls-tls-webpki-roots"], optional = true }
url = { version = "2", optional = true }

[target.'cfg(target_os="linux")'.dependencies]
tray-item = { git = "https://github.com/windoze/tray-item-rs.git", features = ["ksni"], optional = true }
png = { version = "0.17", optional = true }

[target.'cfg(not(target_os="linux"))'.dependencies]
tray-item = { git = "https://github.com/windoze/tray-item-rs.git" }

[build-dependencies]
embed-resource = "2.4"

[features]
default = [
    "rumqttc",
    "clipboard",
    "clipboard-master",
    "gethostname",
    "random-string",
    "tokio-tungstenite",
    "tray-item",
    "png",
    "url",
]
server-only = []
