on: [push]
name: CI

jobs:
  test_and_check:
    name: Test and Check
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - build: macos-x86_64
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get -y update
            sudo apt-get install -y libdbus-1-dev pkg-config libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
            cargo clippy --no-default-features --features server-only -- -D warnings
          fi
          cargo test
          cargo clippy -- -D warnings
